### ISSUE TITLE
Is there any possible get duration via http ?

### ISSUE THREAD

**Issue by kristoff2016** [ddsol/mp3-duration#10]
Hi, thanks for great plugin. is there any possible read duration via http ?  not local files 
thanks

**Comment by ddsol** [comment]
No, but you could probably adapt it to use `ArrayBuffer` yourself. Note that the code uses `Promise`s and generators so it won't work in all browsers. That said, this is only needed to read files without using the Sync functions (which would block the single JS thread). So you could just remove the generator functions and be fine.
