### ISSUE TITLE
exception thrown for a broken header

### ISSUE THREAD

**Issue by mycoboco** [ddsol/mp3-duration#5]
One of my mp3 files has a broken header whose MPEG Audio version ID is 1, and `mp3-duration` throws an exception:

    TypeError: Cannot read property '14' of undefined

because there is no elements for `VxL`_n_ in the `bitRates` object.

How about adding keys for `VxL`_n_ as for `V1Lx` and `V2Lx`?

(I've already [done](https://github.com/mycoboco/mp3-duration/commit/e51c74088b066b12d7db204bde26949005f8bdff) it on my forked version, and can make a PR if you think my fix is okay.)

**Comment by ddsol** [comment]
Sounds good to me. PRS are always welcome.
